name: Deploy Next.js to EC2

on:
  push:
    branches:
      - main  # Deploy when code is pushed to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1  # Adjust if necessary
      EC2_BACKEND_IP: ${{ secrets.EC2_BACKEND_IP }}
      SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

    steps:
      # Checkout code from GitHub repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Set the Node.js version you're using

      # Install dependencies for Next.js
      - name: Install Dependencies
        run: |
          npm install  # This installs the dependencies listed in package.json

      # Build the Next.js app
      - name: Build Next.js app
        run: |
          npm run build  # This will create the `.next` build folder

      # Set up SSH for EC2 deployment
      - name: Set up SSH key
        run: |
          echo "$SSH_KEY" > private_key.pem
          chmod 600 private_key.pem

      # Deploy to EC2 instance
      - name: Deploy Next.js app to EC2
        run: |
          # Copy the Next.js build and necessary files to the EC2 instance
          scp -i private_key.pem -r ./ * ubuntu@$EC2_BACKEND_IP:/var/www/nextjs

          # SSH into EC2, install Node.js, and install dependencies if needed
          ssh -i private_key.pem ubuntu@$EC2_BACKEND_IP "cd /var/www/nextjs && npm install --production"
          
          # Start the Next.js app (with a process manager like PM2 or in a background process)
          ssh -i private_key.pem ubuntu@$EC2_BACKEND_IP "cd /var/www/nextjs && npm run start &"
